import NextAuthProvider from "@/components/providers/next-auth-providers";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";

import { VT323 } from "next/font/google";

const vt = VT323({
  weight: ["400"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          (cn("bg-background min-h-screen font-sans antialiased"), vt.variable)
        }
      >
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
